# Bannerbear API Key
BANNERBEAR_API_KEY = "bb_pr_e341e38d107fcb3b1cb40451488dff"

# Google Gemini API Key
GOOGLE_API_KEY = "AIzaSyCrPNwJY-YNy9h8ijfWhX-ibCGRzmEZW94"

# FreeImage.host API Key
FREEIMAGE_API_KEY = "6d207e02198a847aa98d0a2a901485a5" 